"""empty message

Revision ID: 984c7fa3b6ba
Revises: 0e71f450c57f
Create Date: 2019-02-09 22:37:20.276475

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '984c7fa3b6ba'
down_revision = '0e71f450c57f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tweet', sa.Column('incident', sa.String(length=120), nullable=True))
    op.add_column('tweet', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('tweet', sa.Column('local_time', sa.String(length=10), nullable=True))
    op.add_column('tweet', sa.Column('location', sa.String(length=120), nullable=True))
    op.add_column('tweet', sa.Column('longitude', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tweet', 'longitude')
    op.drop_column('tweet', 'location')
    op.drop_column('tweet', 'local_time')
    op.drop_column('tweet', 'latitude')
    op.drop_column('tweet', 'incident')
    # ### end Alembic commands ###
